import { Check, Clock, Crosshair, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { ProvenanceBadge, SeverityBadge } from "@/components/common/StatusBadges";
import { EmptyState } from "@/components/common/States";
import { storeys } from "@/data/mock";
import type { Evidence, ValidationIssue } from "@/types/infer";

const evidenceMeta: Record<Evidence["kind"], { label: string; className: string }> = {
  "ifc-fact": { label: "Source IFC fact", className: "border-verified/40 text-verified" },
  deterministic: { label: "Deterministic finding", className: "border-primary/40 text-primary" },
  "ai-inference": { label: "AI-assisted inference", className: "border-inferred/45 text-inferred" },
  "human-approved": { label: "Human-approved correction", className: "border-border text-muted-foreground" },
};

export function ValidationIssueDetails({ issue }: { issue: ValidationIssue | null }) {
  if (!issue) {
    return (
      <EmptyState
        icon={<Crosshair className="size-5" />}
        title="No issue selected"
        description="Select an issue to focus the element in the model and review its evidence and proposed correction."
      />
    );
  }

  const storey = storeys.find((s) => s.id === issue.storeyId)?.name ?? "—";

  return (
    <div className="space-y-4 p-3">
      <header className="space-y-2">
        <div className="flex items-start justify-between gap-2">
          <h3 className="text-sm leading-snug font-semibold text-foreground">{issue.title}</h3>
          <SeverityBadge severity={issue.severity} />
        </div>
        <p className="text-xs leading-relaxed text-muted-foreground">{issue.summary}</p>
      </header>

      <dl className="grid grid-cols-2 gap-x-3 gap-y-2 border border-border bg-surface-raised p-2.5 text-xs">
        <Field label="Affected entity" value={issue.entityLabel} />
        <Field label="IFC class" value={issue.entityClass} mono />
        <Field label="Storey" value={storey} />
        <Field label="Category" value={issue.category} />
        <div className="col-span-2">
          <dt className="label-caps text-muted-foreground">IFC GUID</dt>
          <dd className="font-mono text-[11px] break-all text-foreground">{issue.guid}</dd>
        </div>
      </dl>

      <section>
        <h4 className="label-caps mb-1.5 text-muted-foreground">Related entities</h4>
        <ul className="flex flex-wrap gap-1">
          {issue.relatedEntities.map((r) => (
            <li key={r} className="border border-border bg-surface-raised px-1.5 py-0.5 text-[11px] text-muted-foreground">
              {r}
            </li>
          ))}
        </ul>
      </section>

      <section>
        <h4 className="label-caps mb-1.5 text-muted-foreground">Evidence</h4>
        <ul className="space-y-1.5">
          {issue.evidence.map((e) => (
            <li key={e.id} className={`border-l-2 bg-surface-raised py-1.5 pl-2.5 ${evidenceMeta[e.kind].className}`}>
              <p className="text-[11px] font-semibold">{evidenceMeta[e.kind].label}</p>
              <p className="text-xs leading-relaxed text-muted-foreground">{e.detail}</p>
            </li>
          ))}
        </ul>
      </section>

      <section>
        <h4 className="label-caps mb-1 text-muted-foreground">Confidence</h4>
        <div className="flex items-center gap-2">
          <Progress value={issue.confidence * 100} className="h-1.5 flex-1" aria-label="Finding confidence" />
          <span className="font-mono text-xs text-foreground">{(issue.confidence * 100).toFixed(0)}%</span>
          <ProvenanceBadge provenance={issue.provenance} />
        </div>
      </section>

      <section>
        <h4 className="label-caps mb-1 text-muted-foreground">Proposed correction</h4>
        <p className="border border-primary/30 bg-primary/5 p-2.5 text-xs leading-relaxed text-foreground">
          {issue.proposedAction}
        </p>
        <p className="mt-1 text-[11px] text-muted-foreground">
          Proposals are generated by INFER and require human approval before they affect published routing.
        </p>
      </section>

      <div className="flex gap-1.5">
        <Button size="sm" className="flex-1 gap-1.5" onClick={() => toast.success("Correction accepted and queued for recompile.")}>
          <Check className="size-3.5" /> Accept
        </Button>
        <Button size="sm" variant="outline" className="gap-1.5" onClick={() => toast("Correction rejected.")}>
          <X className="size-3.5" /> Reject
        </Button>
        <Button size="sm" variant="ghost" className="gap-1.5" onClick={() => toast("Issue deferred.")}>
          <Clock className="size-3.5" /> Defer
        </Button>
      </div>
    </div>
  );
}

function Field({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div>
      <dt className="label-caps text-muted-foreground">{label}</dt>
      <dd className={`capitalize text-foreground ${mono ? "font-mono text-[11px] normal-case" : ""}`}>{value}</dd>
    </div>
  );
}
